### ISSUE TITLE
Can't import a blog exported via Wordpress's ghost exporter plugin

### ISSUE THREAD

**Issue by mrdomino** [jparyani/GhostSS#21]
Trying to import my blog into a fresh Ghost grain, I see the following error:

```
GET /ghost/api/v0.1/settings/?type=blog%2Ctheme 200 20.425 ms - -

ERROR: Cannot read property 'users' of undefined 

 TypeError: Cannot read property 'users' of undefined
    at DataImporter.doUserImport (/core/server/data/import/data-importer.js:37:18)
    at Transaction_SQLite3.container (/core/server/data/import/data-importer.js:80:18)
    at Transaction_SQLite3.Transaction.initiateDeferred (/node_modules/knex/lib/transaction.js:58:21)
    at /node_modules/knex/lib/transaction.js:90:22
From previous event:
    at Transaction_SQLite3.Transaction.then (/node_modules/knex/lib/transaction.js:85:6)
    at /core/server/data/import/data-importer.js:140:12 

POST /ghost/api/v0.1/db/ 500 38.482 ms - 102
```

**Comment by jparyani** [comment]
This may be due to the Ghost Sandstorm port being so out of date. Updating it is near the top of my todo list, but I keep getting distracted with other things :)

**Comment by mrdomino** [comment]
Very likely -- I can import the same file successfully on a fresh install on ghost.org.
